# RIDOS OS v1.1 — LightDM Login Screen
# Copyright (C) 2026 RIDOS OS Project — GPL v3

[greeter]
background        = /usr/share/backgrounds/ridos/ridos-wallpaper.svg
logo              = /usr/share/ridos/branding/ridos-icon.svg
theme-name        = Greybird-dark
icon-theme-name   = Papirus-Dark
font-name         = Monospace 11
cursor-theme-name = Adwaita
cursor-theme-size = 24
panel-position    = bottom
hide-user-image   = false
default-user-image = /usr/share/ridos/branding/ridos-icon.svg
indicators        = ~host;~spacer;~clock;~spacer;~power
clock-format      = %H:%M  —  %A, %d %B %Y
